### ISSUE TITLE
Considering its capability in the image enhancement models

### ISSUE THREAD

**Issue by trungpx** [hee-suk-yoon/ESD#9]
Thanks for the code. Have the authors tried testing it on other domains such as image/video restoration, super-resolution, and representation learning frameworks (MoCo, DINO, iBOT, ...)? I believe that the calibration can help guide the discriminative process of the real and fake outputs.

**Comment by hee-suk-yoon** [comment]
We have not tried applying to other domains but I think the application of ESD to the mentioned tasks would be interesting to try.
